Repository DataDog/java-profiler, pull requests merged in 2023-08, with the labels that each got.

#6 Disable stresstests in GHA for perf reasons
  .github/workflows/ci.yml
Labels: mergequeue-status: in_progress

#5 Resolve jmethodID issues with class strong reference cache
  .github/workflows/ci.yml
  ddprof-lib/src/main/cpp/arch.h
  ddprof-lib/src/main/cpp/arguments.cpp
  ddprof-lib/src/main/cpp/arguments.h
  ddprof-lib/src/main/cpp/classRefCache.cpp
  ddprof-lib/src/main/cpp/classRefCache.h
  ddprof-lib/src/main/cpp/flightRecorder.cpp
  ddprof-lib/src/main/cpp/flightRecorder.h
  ddprof-lib/src/main/cpp/jfrMetadata.cpp
  ddprof-lib/src/main/cpp/jfrMetadata.h
  ddprof-lib/src/main/cpp/livenessTracker.cpp
  ddprof-lib/src/main/cpp/livenessTracker.h
  ddprof-lib/src/main/cpp/methodCache.cpp
  ddprof-lib/src/main/cpp/methodCache.h
  ddprof-lib/src/main/cpp/objectSampler.cpp
  ddprof-lib/src/main/cpp/profiler.cpp
  ddprof-lib/src/main/cpp/profiler.h
  ddprof-lib/src/main/cpp/vmEntry.cpp
  ddprof-lib/src/main/cpp/vmEntry.h
  ddprof-lib/src/main/cpp/vmStructs.cpp
  ddprof-lib/src/main/cpp/vmStructs.h
  ddprof-lib/src/test/cpp/ddprof_ut.cpp
  ddprof-test/build.gradle
  ddprof-test/src/test/java/com/datadoghq/profiler/AbstractProfilerTest.java
Labels: mergequeue-status: rejected

#13 add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: mergequeue-status: rejected

#14 Remove class ref cache because it is too expensive
  ddprof-lib/src/main/cpp/classRefCache.cpp
  ddprof-lib/src/main/cpp/classRefCache.h
  ddprof-lib/src/main/cpp/flightRecorder.cpp
  ddprof-lib/src/main/cpp/flightRecorder.h
  ddprof-lib/src/main/cpp/livenessTracker.cpp
  ddprof-lib/src/main/cpp/livenessTracker.h
  ddprof-lib/src/main/cpp/objectSampler.cpp
Labels: mergequeue-status: removed
